# Generated by Django 4.1.4 on 2022-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje', models.CharField(max_length=50)),
                ('habilidad', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
    ]
